name: network_handler
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  fpdart: ^1.2.0
  hive_flutter: ^1.1.0
  http: ^1.6.0
  path_provider: ^2.1.5
  talker: ^5.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
